# Generated by Django 5.0.2 on 2024-02-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='faerga')),
                ('email', models.EmailField(max_length=254, verbose_name='gasdfasd')),
                ('address', models.TextField(verbose_name='sdfadsf')),
                ('phone', models.CharField(max_length=20, verbose_name='sdfasdf')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
